GET https://api.jusfuny.com/users/09c56f0c-dcbc-449d-b98f-e157e9e9ead8/feed
Authorization: eyJhbGciOiJIUzI1NiIsImtpZCI6ImVYYlhUVjFCbGdtN1FUOG8iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzA1MzM0MjAyLCJpYXQiOjE3MDUzMzA2MDIsImlzcyI6Imh0dHBzOi8vYnFndnV0YnN4Yml4ZnR1Z2N6YmYuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6IjA5YzU2ZjBjLWRjYmMtNDQ5ZC1iOThmLWUxNTdlOWU5ZWFkOCIsImVtYWlsIjoiZWRvYXJkby50YWthbmVuQGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnt9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzA1MzMwNjAyfV0sInNlc3Npb25faWQiOiIwY2JiNWZhNS1iNWZlLTQxYzQtYWVlMC0yMmQ0NGI3MWNiOTYifQ.wmQndAUmodBxk-7n0YlklGqK7RbDOnrj4mZR_xI61h8

###
POST https://api.jusfuny.com/users/e225debf-7f48-49c8-a759-f7963f089b9b/posts/24/reactions
Authorization: eyJhbGciOiJIUzI1NiIsImtpZCI6ImVYYlhUVjFCbGdtN1FUOG8iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzA1MzM0MjAyLCJpYXQiOjE3MDUzMzA2MDIsImlzcyI6Imh0dHBzOi8vYnFndnV0YnN4Yml4ZnR1Z2N6YmYuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6IjA5YzU2ZjBjLWRjYmMtNDQ5ZC1iOThmLWUxNTdlOWU5ZWFkOCIsImVtYWlsIjoiZWRvYXJkby50YWthbmVuQGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnt9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzA1MzMwNjAyfV0sInNlc3Npb25faWQiOiIwY2JiNWZhNS1iNWZlLTQxYzQtYWVlMC0yMmQ0NGI3MWNiOTYifQ.wmQndAUmodBxk-7n0YlklGqK7RbDOnrj4mZR_xI61h8
Content-Type: application/json

{

}